[package]
  cjc-version = "1.0.3"
  name = "lanlu"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "-larchive -lavif -lpng16 -lz"
  package-configuration = {}

[dependencies]
  cjoy = { git = "https://gitcode.com/Cangjie-SIG/cjoy.git", branch = "main" }
  opengauss = {git = "https://gitcode.com/copur/opengauss-driver.git", output-type = "static", branch="master"}
  cjdotenv = { git = "https://gitcode.com/Cangjie-SIG/cjdotenv.git", tag = "master" }
  ahash = { git = "https://gitcode.com/OpenCangjieCommunity/ahash.git", tag = "master" }
  cjcron = { path = "packages/cjcron" }
  epub = { path = "packages/epub" }
  archive_ffi = { path = "packages/archive_ffi" }
  avif_ffi = { path = "packages/avif_ffi" }
  png_ffi = { path = "packages/png_ffi" }
  semver = { path = "packages/semver" }

[target]
  [target.x86_64-unknown-linux-gnu]
    compile-option = "--static -O2 --cfg \"ohos=false\""
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}/linux_x86_64_llvm/static/stdx" ]
